-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    "uId" serial NOT NULL,
    username character varying(64) NOT NULL,
    password character varying(64) NOT NULL,
    "fridgeIngredientsId" serial NOT NULL,
    PRIMARY KEY ("uId"),
    CONSTRAINT "fridgeIngredientsId" UNIQUE ("fridgeIngredientsId"),
    CONSTRAINT username UNIQUE (username)
);

COMMENT ON COLUMN public."Users".username
    IS 'musi być unikalny';

CREATE TABLE IF NOT EXISTS public."Ingredients"
(
    "ingredientID" serial NOT NULL,
    "ingredientName" character varying(32) NOT NULL,
    "quantityType" character varying(20) NOT NULL,
    PRIMARY KEY ("ingredientID")
);

CREATE TABLE IF NOT EXISTS public."IngredientList"
(
    "ingredientListId" serial NOT NULL,
    "ingredientId" serial NOT NULL,
    "ingredientQuantity" serial NOT NULL,
    id serial NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON COLUMN public."IngredientList".id
    IS 'Zrobione by ORM nie oszalał';

CREATE TABLE IF NOT EXISTS public."Recipes"
(
    "recipeId" serial NOT NULL,
    "recipeSteps" character varying(1024) NOT NULL,
    "recipeDescription" character varying(280) NOT NULL,
    "ingredientListId" serial NOT NULL,
    "ownerId" serial NOT NULL,
    PRIMARY KEY ("recipeId"),
    CONSTRAINT "ingredienListId" UNIQUE ("ingredientListId")
);

ALTER TABLE IF EXISTS public."IngredientList"
    ADD FOREIGN KEY ("ingredientId")
    REFERENCES public."Ingredients" ("ingredientID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."IngredientList"
    ADD FOREIGN KEY ("ingredientListId")
    REFERENCES public."Recipes" ("ingredientListId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."IngredientList"
    ADD FOREIGN KEY ("ingredientListId")
    REFERENCES public."Users" ("fridgeIngredientsId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Recipes"
    ADD CONSTRAINT "uId" FOREIGN KEY ("ownerId")
    REFERENCES public."Users" ("uId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;